### ISSUE TITLE
[[AFSoundManager sharedManager]forceOutputToBuiltInSpeakers] not working

### ISSUE THREAD

**Issue by hcivelek** [AlvaroFranco/AFSoundManager#29]
I try to force built in speaker when headphone jack plugged in, but nothing happen. Did I miss something?

**Comment by AlvaroFranco** [comment]
Looks like it broke down on iOS 8, I'm looking into it.

**Comment by hcivelek** [comment]
Thank you, I'll wait for your reply :)

**Comment by AlvaroFranco** [comment]
I haven't been able to find a workaround on iOS 8. I've dropped that feature support on the version since *almost* nobody was using it. Still, if you need that even for iOS 7, it's pretty easy to implement it by yourself, just import ```AFAudioRouter ```
