### ISSUE TITLE
Be able to record to a different directory than /Documents

### ISSUE THREAD

**Issue by diogeneshamilton** [AlvaroFranco/AFSoundManager#31]
Especially since the default place to play from is [[NSBundle mainBundle] resourcePath], which is a different place.

**Comment by AlvaroFranco** [comment]
Feel free to change the line 217 at the AFSoundManager.m (https://github.com/AlvaroFranco/AFSoundManager/blob/master/Classes/AFSoundManager.m#L217). Anyway, the current version is deprecated and the v2 is going to be pushed anytime this week, maybe tomorrow. Stay tuned!

**Comment by diogeneshamilton** [comment]
Sounds good, yeah I figured this would be fixed in later versions.

**Comment by AlvaroFranco** [comment]
Fixed on the v2 :smiley:
