### ISSUE TITLE
Stop Sound

### ISSUE THREAD

**Issue by rafaelmoraes83** [AlvaroFranco/AFSoundManager#39]
How can I stop music?

Thanks!

**Comment by Broich** [comment]
In case you enqueue an AFSoundItem into a AFSoundQueue you simple call `[myAFSoundQueue pause]` (which is equivalent to stop). However there seems to be no method on AFSoundItem itself? @AlvaroFranco

**Comment by rafaelmoraes83** [comment]
Thanks Broich!!!
