### ISSUE TITLE
How to seek when using a queue?

### ISSUE THREAD

**Issue by noveleven** [AlvaroFranco/AFSoundManager#49]
Hi, how to seek when using a queue, i found AFSoundPlayback class has a method named "playAtSecond:", but AFSoundQueue class doesn't have.

**Comment by DevelopIdeas** [comment]
I got around this gracefully by creating the following category (AFSoundQueue+Private.h):
`#import <AFSoundManager/AFSoundManager.h>`
`@interface AFSoundQueue(Private)`
`@property (nonatomic, strong) AFSoundPlayback *queuePlayer;`
`@end`
With this you can do something like:
`[audioPlayer.queuePlayer playAtSecond:0];`
